version: '3'
services:
    vlc:
        container_name: vlc
        restart: always
        build:
            context: vlc/
            dockerfile: Dockerfile
        ports:
            - "8083:8083"
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./nginx/data/:/var/www/html
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
